apiVersion: v1
kind: Service
metadata:
  name: placeholder-servicename
  labels:
    app: placeholder-app
  namespace: placeholder-namespace
  ownerReferences:
    - apiVersion: theia.cloud/v1beta9
      kind: Session
      name: placeholder
      uid: placeholder
spec:
  ports:
    - name: java-ls
      port: placeholder-java-port
      protocol: TCP
      targetPort: placeholder-java-port
    - name: rust-ls
      port: placeholder-rust-port
      protocol: TCP
      targetPort: placeholder-rust-port
  selector:
    app: placeholder-app
  type: ClusterIP
